site_name: "Портфолио Бондаревой Ирины"
site_description: "Сайт-портфолио студентки с лабораторными работами"
site_author: "Бондарева Ирина"

theme:
  name: material
  language: ru
  palette:
    - scheme: default
      primary: green
      accent: light-green
      toggle:
        icon: material/brightness-7
        name: Переключить на темную тему
    - scheme: slate
      primary: green
      accent: light-green
      toggle:
        icon: material/brightness-4
        name: Переключить на светлую тему

nav:
  - Главная: index.md
  - Об авторе: about.md
  - Лабораторные работы:
    - Лабораторная работа №1: labs/lab1.md
    - Лабораторная работа №2: labs/lab2.md
    - Лабораторная работа №3: labs/lab3.md
    - Лабораторная работа №4: labs/lab4.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true